version: '3.9'

services:
  product_service:
    container_name: payment_service
    build: payment_service
    ports:
      - "8001:8000"

  category_service:
    container_name: payment_gateway_service
    build: payment_gateway_service
    ports:
      - "8002:8000"

  api_gateway:
    image: devopsfaith/krakend:watch
    container_name: api_gateway
    volumes:
      - ./krakenD:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    links:
      - product_service
      - category_service
    depends_on:
      - product_service
      - category_service