name: CI tikhonov

on:
  push:
    branches: [ "master" ]


jobs:

  test-tikhonov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the test Docker image
      run: | 
        cd  payment_service
        docker build . --file Dockerfile.test -t test-tikhonov
    - name: Run the test Docker image
      run: |
        docker run test-tikhonov
  
  publish-image:

    needs: test-tikhonov

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.TOKEN_DOCKER_HUB }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./payment_service
          push: true
          tags: gby211757/micro-tikhonov:latest
